# This is a basic workflow to help you get started with Actions

name: Stack-Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # # install mosquitto
      # - name: Install mosquitto
      #   run: sudo apt update && sudo apt-get install -y mosquitto

      # install mosquitto clients
      - name: Install mosquitto clients
        run: sudo apt update && sudo apt-get install -y mosquitto-clients

      # # run mosquitto in verbose mode
      # - name: ReStart mosquitto
      #   run: |
      #     sudo service mosquitto stop
      #     sudo systemctl stop mosquitto.service
      #     mosquitto -d -v -p 1888

      # build and run stack
      - name: Compose up
        run: docker-compose -f "docker-compose.yml" up -d --build

      # show running containers
      - name: show running containers
        run: docker ps

      # check that mosquitto can publish a message
      - name: Mosquitto publish
        run: mosquitto_pub -h 127.0.0.1 -p 1883 -u mqtt -P password -t mig-stack/messages -m "hello runner" -d

      # check influxdb
      - name: Check database created in influxdb
        run: docker exec migstack_influxdb_1 influx -execute "SHOW DATABASES" | grep -q MIGStack

      # wait for fowarder
      - name: wait for and check forwarder
        run: mosquitto_sub -h 127.0.0.1 -p 1883 -u mqtt -P password -t mig-stack/messages -C 1 | grep -q Forwarder
      
      # check forwarder forwards messages
      - name: publish sensor readings message
        run: |
          sleep 10
          MESSAGE="{\"meta-data\":{\"device\":\"test\"},\"measures\":{\"sensor1\":5,\"sensor2\":43}}"
          mosquitto_pub -h 127.0.0.1 -p 1883 -u mqtt -P password -t mig-stack/test/sensor-reading -m $MESSAGE -d
          
      - name: Check sensor-readings table exists
        run: |
          sleep 10
          docker exec migstack_influxdb_1 influx -database MIGStack -execute "SHOW MEASUREMENTS" | grep -q sensor-readings

      - name: Check sensor values in table
        run: |
          docker exec migstack_influxdb_1 influx -database "MIGStack" -execute "SELECT SUM(sensor1) FROM \"2_weeks\".\"sensor-readings\" WHERE device = 'test'" | grep -q 5
          docker exec migstack_influxdb_1 influx -database "MIGStack" -execute "SELECT SUM(sensor2) FROM \"2_weeks\".\"sensor-readings\" WHERE device = 'test'" | grep -q 43
